import { Figtree } from 'next/font/google'
import Sidebar from '@/app/components/Sidebar'
// import { SessionProvider } from "next-auth/react"

import './globals.css'
import NextAuthProvider from './auth-provider/auth-provider'
import AuthContext from './(site)/messenger/context/AuthContext'
import ToasterContext from './(site)/messenger/context/ToasterContext'
import ActiveStatus from './(site)/messenger/components/ActiveStatus'

const font = Figtree({ subsets: ['latin'] })

export const metadata = {
    title: 'TransAppT',
    description: 'Aplicacion de transporte maritimo',
}

export const revalidate = 0;

export default async function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="es">
            <body className={`${font.className} antialiased`}>
                <AuthContext>
                    <ToasterContext />
                    <ActiveStatus />
                    <NextAuthProvider >
                        <Sidebar >
                            {children}
                        </Sidebar>
                    </NextAuthProvider>
                </AuthContext>
            </body>
        </html>
    )
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
